Repository DeveloperAcademy-POSTECH/MC3-Team7-MoTe, pull requests merged in 2022-07, with the labels that each got.

#7 [D0] 탭바 구현
  Alarmi/Alarmi.xcodeproj/project.pbxproj
  Alarmi/Alarmi/Sources/Global/Extensions/UITabBarItem+.swift
  Alarmi/Alarmi/Sources/Global/Extensions/UIViewController+.swift
  Alarmi/Alarmi/Sources/SceneDelegate.swift
  Alarmi/Alarmi/Sources/ViewControllers/MainTabBarController.swift
  Alarmi/Alarmi/Sources/ViewControllers/RecordViewController.swift
  Alarmi/Alarmi/Sources/ViewControllers/TodayViewController.swift
Labels: 🌳WOODY, P3, D0

#11 [D-1] 오늘 탭 화면 구성
  Alarmi/Alarmi.xcodeproj/project.pbxproj
  Alarmi/Alarmi/Sources/Global/Extensions/UILabel+.swift
  Alarmi/Alarmi/Sources/Global/Extensions/UIStackView+.swift
  Alarmi/Alarmi/Sources/Global/Extensions/UITabBarItem+.swift
  Alarmi/Alarmi/Sources/Global/Extensions/UIView+.swift
  Alarmi/Alarmi/Sources/ViewControllers/MainTabBarController.swift
  Alarmi/Alarmi/Sources/ViewControllers/TodayViewController.swift
Labels: 🌳WOODY, D-1, P3

#9 [D0] auto-assign 추가
  .github/.auto-assign.yml
Labels: 📝Docs, 🧸BROWN, D0, ⛏Setting

#20 [D0] 알림 화면 구성
  Alarmi/Alarmi.xcodeproj/project.pbxproj
  Alarmi/Alarmi/Sources/Global/Components/AMButton.swift
  Alarmi/Alarmi/Sources/Global/Extensions/UIFont+.swift
  Alarmi/Alarmi/Sources/Global/Extensions/UILabel+.swift
  Alarmi/Alarmi/Sources/ViewControllers/RecordViewController.swift
  Alarmi/Alarmi/Sources/ViewControllers/SettingAlarm/SettingNotifyViewController.swift
  Alarmi/Alarmi/Sources/ViewControllers/SettingAlarm/Supporting Views/AlarmAgainSetView.swift
  Alarmi/Alarmi/Sources/ViewControllers/SettingAlarm/Supporting Views/AlarmSetView.swift
Labels: 🌳WOODY, D0

#22 [D0] 연락 미루기 UI 구성 및 화면 연결
  Alarmi/Alarmi.xcodeproj/project.pbxproj
  Alarmi/Alarmi/Sources/ViewControllers/CallDelayViewController.swift
  Alarmi/Alarmi/Sources/ViewControllers/TodayViewController.swift
Labels: 🌳WOODY, D-1

#16 [D-2] 초기 설정 완료 온보딩 화면 구현
  Alarmi/.swiftlint.yml
  Alarmi/Alarmi.xcodeproj/project.pbxproj
  Alarmi/Alarmi/Sources/Global/Extensions/UIViewController+.swift
  Alarmi/Alarmi/Sources/ViewControllers/SettingCompleteViewController.swift
Labels: 🥑AVO, D-2

#23 [D-2] 설정 화면 구현
  Alarmi/Alarmi.xcodeproj/project.pbxproj
  Alarmi/Alarmi/Sources/ViewControllers/SettingViewController.swift
Labels: 🥑AVO, D-2

#25 [D-1] 현재위치 설정 화면 구현
  Alarmi/Alarmi.xcodeproj/project.pbxproj
  Alarmi/Alarmi/Sources/ViewControllers/CurrentLocationView/SettingLocationCollectionViewCell.swift
  Alarmi/Alarmi/Sources/ViewControllers/CurrentLocationView/SettingLocationViewController.swift
Labels: ✨Feature, 🧸BROWN, D-1, P1

#28 [D0] 초기 목표 날짜 설정 온보딩 화면 구현
  Alarmi/Alarmi.xcodeproj/project.pbxproj
  Alarmi/Alarmi/Sources/SettingPlan.storyboard
  Alarmi/Alarmi/Sources/ViewControllers/SettingPlanViewController.swift
Labels: 🐻GRIZZLY, D0

#50 [D0] 코디네이터 패턴 적용
  Alarmi/Alarmi.xcodeproj/project.pbxproj
  Alarmi/Alarmi/Resources/CallTime.storyboard
  Alarmi/Alarmi/Resources/SettingPlan.storyboard
  Alarmi/Alarmi/Sources/App/AppCoordinator.swift
  Alarmi/Alarmi/Sources/Global/Coordinator.swift
  Alarmi/Alarmi/Sources/Global/Extensions/UIFont+.swift
  Alarmi/Alarmi/Sources/MainTab/Record/RecordViewController.swift
  Alarmi/Alarmi/Sources/MainTab/Tab/MainTabBarController.swift
  Alarmi/Alarmi/Sources/MainTab/Tab/MainTabCoordinator.swift
  Alarmi/Alarmi/Sources/MainTab/Today/CallDelayViewController.swift
  Alarmi/Alarmi/Sources/MainTab/Today/SettingViewController.swift
  Alarmi/Alarmi/Sources/MainTab/Today/TodayViewController.swift
  Alarmi/Alarmi/Sources/Register/RegisterCallTimeViewController.swift
  Alarmi/Alarmi/Sources/Register/RegisterCompleteViewController.swift
  Alarmi/Alarmi/Sources/Register/RegisterCoordinator.swift
  Alarmi/Alarmi/Sources/Register/RegisterNotifyViewController.swift
  Alarmi/Alarmi/Sources/Register/RegisterPlanViewController.swift
  Alarmi/Alarmi/Sources/Register/Supporting Views/AlarmAgainSetView.swift
  Alarmi/Alarmi/Sources/Register/Supporting Views/AlarmSetView.swift
  Alarmi/Alarmi/Sources/Register/Supporting Views/CurrentLocationView/RegisterLocationCollectionViewCell.swift
  Alarmi/Alarmi/Sources/Register/Supporting Views/CurrentLocationView/RegisterLocationViewController.swift
  Alarmi/Alarmi/Sources/SceneDelegate.swift
  Alarmi/Alarmi/Sources/ViewController.swift
Labels: 🌳WOODY, D0, ⛏Setting

#54 [D0] 데이터 연결 생성.
  Alarmi/Alarmi.xcodeproj/project.pbxproj
  Alarmi/Alarmi/Resources/SettingPlan.storyboard
  Alarmi/Alarmi/Sources/Models/Alarm.swift
  Alarmi/Alarmi/Sources/Register/RegisterCallTimeViewController.swift
  Alarmi/Alarmi/Sources/Register/RegisterCompleteViewController.swift
  Alarmi/Alarmi/Sources/Register/RegisterCoordinator.swift
  Alarmi/Alarmi/Sources/Register/RegisterNotifyViewController.swift
  Alarmi/Alarmi/Sources/Register/RegisterPlanViewController.swift
  Alarmi/Alarmi/Sources/Register/RegisterViewModel.swift
Labels: 🐻GRIZZLY, D0

#61 [D0] auto assign 수정
  .github/auto-assign.yml
Labels: 🧸BROWN, D0, ⛏Setting

#53 [D-1] 설정 화면 리팩토링 및 '앱 초기화' 추가
  Alarmi/Alarmi/Sources/MainTab/Today/SettingViewController.swift
Labels: 🥑AVO, D-1

#62 [D0]통화 시간 default값 생성
  Alarmi/Alarmi/Sources/Register/RegisterCallTimeViewController.swift
Labels: ♻️Refactoring, 💰WONNY, D0

#73 [D0] MoTe Scene 템플릿 추가
  Alarmi/Alarmi/Sources/Register/aViewController.swift
  Alarmi/Alarmi/Sources/Register/aViewModel.swift
  Script/Templates/Makefile
  Script/Templates/MoTe Template/MoTe Scene.xctemplate/TemplateIcon-1016.png
  Script/Templates/MoTe Template/MoTe Scene.xctemplate/TemplateIcon-1016@2x.png
  Script/Templates/MoTe Template/MoTe Scene.xctemplate/TemplateInfo.plist
  Script/Templates/MoTe Template/MoTe Scene.xctemplate/___FILEBASENAME___ViewController.swift
  Script/Templates/MoTe Template/MoTe Scene.xctemplate/___FILEBASENAME___ViewModel.swift
Labels: 🌳WOODY, D0

#71 [D0] CallTime 설정 뷰 디자인 수정
  Alarmi/Alarmi/Resources/CallTime.storyboard
  Alarmi/Alarmi/Sources/Register/RegisterCallTimeViewController.swift
Labels: ♻️Refactoring, 💰WONNY, D0

#87 [D0] 목표 설정 화면 디자인 수정
  Alarmi/Alarmi/Resources/SettingPlan.storyboard
  Alarmi/Alarmi/Sources/Register/RegisterPlanViewController.swift
Labels: ✨Feature, 🥑AVO, D0

#88 [D0] 기록하기 UI
  Alarmi/Alarmi.xcodeproj/project.pbxproj
  Alarmi/Alarmi/Sources/Global/Constant.swift
  Alarmi/Alarmi/Sources/Global/Manager/CallTimeManager.swift
  Alarmi/Alarmi/Sources/Global/Manager/DateManager.swift
  Alarmi/Alarmi/Sources/Global/Protocols/Coordinator.swift
  Alarmi/Alarmi/Sources/Global/Protocols/UserDefaultsManager.swift
  Alarmi/Alarmi/Sources/MainTab/Record/RecordModel.swift
  Alarmi/Alarmi/Sources/MainTab/Record/RecordViewController.swift
  Alarmi/Alarmi/Sources/MainTab/Record/RecordViewModel.swift
  Alarmi/Alarmi/Sources/MainTab/Record/Supporting Views/FrequencyContainerView.swift
  Alarmi/Alarmi/Sources/MainTab/Record/Supporting Views/FrequencyView.swift
  Alarmi/Alarmi/Sources/MainTab/Record/Supporting Views/PurposeContainerView.swift
  Alarmi/Alarmi/Sources/MainTab/Record/Supporting Views/RecentAchieveContainerView.swift
  Alarmi/Alarmi/Sources/MainTab/Tab/MainTabCoordinator.swift
  Alarmi/Alarmi/Sources/MainTab/Today/SettingViewController.swift
  Alarmi/Alarmi/Sources/Models/CallDate.swift
  Alarmi/Alarmi/Sources/Models/Frequency.swift
  Alarmi/Alarmi/Sources/Models/Goal.swift
  Alarmi/Alarmi/Sources/Models/GoalTime.swift
  Alarmi/Alarmi/Sources/Register/RegisterPlanViewController.swift
  Alarmi/AlarmiWidget/AlarmiWidget.swift
  Alarmi/AlarmiWidget/Assets.xcassets/AccentColor.colorset/Contents.json
  Alarmi/AlarmiWidget/Assets.xcassets/AppIcon.appiconset/Contents.json
  Alarmi/AlarmiWidget/Assets.xcassets/Contents.json
  Alarmi/AlarmiWidget/Assets.xcassets/WidgetBackground.colorset/Contents.json
  Alarmi/AlarmiWidget/Assets.xcassets/comfort-zone.imageset/Contents.json
  Alarmi/AlarmiWidget/Assets.xcassets/comfort-zone.imageset/comfort-zone.png
  Alarmi/AlarmiWidget/Assets.xcassets/sleeping.imageset/Contents.json
  Alarmi/AlarmiWidget/Assets.xcassets/sleeping.imageset/sleeping.png
  Alarmi/AlarmiWidget/Assets.xcassets/work-in-progress.imageset/Contents.json
  Alarmi/AlarmiWidget/Assets.xcassets/work-in-progress.imageset/work-in-progress.png
  Alarmi/AlarmiWidget/FamilyState.intentdefinition
  Alarmi/AlarmiWidget/Info.plist
Labels: 🌳WOODY, D0

#89 [D0] 설정 화면 - 알림 설정 뷰 추가
  Alarmi/Alarmi.xcodeproj/project.pbxproj
  Alarmi/Alarmi/Sources/MainTab/Setting/AlarmSettingView.swift
  Alarmi/Alarmi/Sources/MainTab/Setting/SettingViewController.swift
  Alarmi/Alarmi/Sources/MainTab/Setting/SettingViewModel.swift
  Alarmi/Alarmi/Sources/MainTab/Tab/MainTabCoordinator.swift
  Alarmi/Alarmi/Sources/MainTab/Today/SettingViewController.swift
Labels: ✨Feature, 🥑AVO, D0

#95 [D0] UserDefaults 사용성 개선
  Alarmi/Alarmi.xcodeproj/project.pbxproj
  Alarmi/Alarmi/Sources/Global/Extensions/UserDefaults+Codable.swift
  Alarmi/Alarmi/Sources/Global/Helper/Constant.swift
  Alarmi/Alarmi/Sources/Global/Helper/UserDefaultsKey.swift
  Alarmi/Alarmi/Sources/Global/Manager/AlarmUserDefaults.swift
  Alarmi/Alarmi/Sources/Global/Manager/CallDateUserDefaults.swift
  Alarmi/Alarmi/Sources/Global/Manager/CallTimeManager.swift
  Alarmi/Alarmi/Sources/Global/Manager/CallTimeUserDefaults.swift
  Alarmi/Alarmi/Sources/Global/Manager/DateManager.swift
  Alarmi/Alarmi/Sources/Global/Manager/GoalTimeUserDefaults.swift
  Alarmi/Alarmi/Sources/Global/Protocols/UserDefaultsManager.swift
  Alarmi/Alarmi/Sources/MainTab/Record/RecordModel.swift
  Alarmi/Alarmi/Sources/MainTab/Record/RecordViewController.swift
  Alarmi/Alarmi/Sources/MainTab/Record/RecordViewModel.swift
  Alarmi/Alarmi/Sources/MainTab/Tab/MainTabCoordinator.swift
  Alarmi/Alarmi/Sources/Register/RegisterCallTimeViewController.swift
  Alarmi/Alarmi/Sources/Register/RegisterCallTimeViewModel.swift
  Alarmi/Alarmi/Sources/Register/RegisterCoordinator.swift
  Alarmi/AlarmiWidget/AlarmiWidget.swift
Labels: 🌳WOODY, D0

#96 [D0] 구조 개선
  Alarmi/Alarmi.xcodeproj/project.pbxproj
  Alarmi/Alarmi/Resources/SettingPlan.storyboard
  Alarmi/Alarmi/Sources/MainTab/Tab/MainTabCoordinator.swift
  Alarmi/Alarmi/Sources/Register/RegisterCallTimeViewController.swift
  Alarmi/Alarmi/Sources/Register/RegisterCoordinator.swift
  Alarmi/Alarmi/Sources/Register/RegisterPlanViewController.swift
  Alarmi/Alarmi/Sources/Register/RegisterPlanViewModel.swift
  Alarmi/Alarmi/Sources/Register/Supporting Views/AlarmAgainSetView.swift
  Alarmi/Alarmi/Sources/Register/Supporting Views/AlarmSetView.swift
  Alarmi/Alarmi/Sources/Register/Supporting Views/CurrentLocationView/RegisterLocationCollectionViewCell.swift
  Alarmi/Alarmi/Sources/Register/Supporting Views/CurrentLocationView/RegisterLocationViewController.swift
Labels: ♻️Refactoring, 🌳WOODY, D0

#101 [D0] auto-assign -> CODEOWNERS로 변경 (리뷰어 자동추가 수정)
  .github/CODEOWNERS
  .github/auto-assign.yml
Labels: 🧸BROWN, D0, ⛏Setting

#100 [D0] 시간에 따라 팬더, 텍스트 바뀌는 기능 추가
  Alarmi/Alarmi/Resources/Assets.xcassets/sleeping.imageset/Contents.json
  Alarmi/Alarmi/Resources/Assets.xcassets/sleeping.imageset/Image.png
  Alarmi/Alarmi/Resources/Assets.xcassets/waiting.imageset/Contents.json
  Alarmi/Alarmi/Resources/Assets.xcassets/waiting.imageset/Image.png
  Alarmi/Alarmi/Resources/Assets.xcassets/working.imageset/Contents.json
  Alarmi/Alarmi/Resources/Assets.xcassets/working.imageset/Image.png
  Alarmi/Alarmi/Sources/MainTab/Today/TodayViewController.swift
  Alarmi/Alarmi/Sources/Register/Supporting Views/TodayDdayView.swift
Labels: ✨Feature, 🧸BROWN, D0

#97 [D0] 오늘 탭 UI 구현
  Alarmi/Alarmi.xcodeproj/project.pbxproj
  Alarmi/Alarmi/Resources/Assets.xcassets/sleeping.imageset/Contents.json
  Alarmi/Alarmi/Resources/Assets.xcassets/sleeping.imageset/Image.png
  Alarmi/Alarmi/Resources/Assets.xcassets/waiting.imageset/Contents.json
  Alarmi/Alarmi/Resources/Assets.xcassets/waiting.imageset/Image.png
  Alarmi/Alarmi/Resources/Assets.xcassets/working.imageset/Contents.json
  Alarmi/Alarmi/Resources/Assets.xcassets/working.imageset/Image.png
  Alarmi/Alarmi/Sources/MainTab/Today/SupportingViews/TodayDdayView.swift
  Alarmi/Alarmi/Sources/MainTab/Today/TodayViewController.swift
  Alarmi/Alarmi/Sources/MainTab/Today/TodayViewModel.swift
Labels: ✨Feature, 🧸BROWN, P1, D0

#99 [D0] 설정 화면 - 전화 시간 설정 + 목표 설정 UI 구현
  Alarmi/Alarmi.xcodeproj/project.pbxproj
  Alarmi/Alarmi/Sources/MainTab/Setting/SettingViewController.swift
  Alarmi/Alarmi/Sources/MainTab/Setting/SettingViewModel.swift
  Alarmi/Alarmi/Sources/MainTab/Setting/Supporting Views/AlarmSettingBoxView.swift
  Alarmi/Alarmi/Sources/MainTab/Setting/Supporting Views/CallTimeSettingBoxView.swift
  Alarmi/Alarmi/Sources/MainTab/Setting/Supporting Views/GoalSettingBoxView.swift
Labels: ✨Feature, 🥑AVO, D0

#104 [D0] 설정 완료 화면 디자인 수정
  Alarmi/Alarmi.xcodeproj/project.pbxproj
  Alarmi/Alarmi/Sources/Global/Manager/UserNotificationManager.swift
  Alarmi/Alarmi/Sources/Register/RegisterCompleteViewController.swift
  Alarmi/Alarmi/Sources/Register/aViewController.swift
  Alarmi/Alarmi/Sources/Register/aViewModel.swift
Labels: ✨Feature, 🥑AVO, D0

#107 [D0] Date 코드 개선 및 빈도 화면 개선
  Alarmi/.swiftlint.yml
  Alarmi/Alarmi.xcodeproj/project.pbxproj
  Alarmi/Alarmi/Sources/Global/Extensions/Date+.swift
  Alarmi/Alarmi/Sources/Global/Manager/DateManager.swift
  Alarmi/Alarmi/Sources/MainTab/Record/RecordViewModel.swift
  Alarmi/Alarmi/Sources/MainTab/Record/Supporting Views/FrequencyView.swift
Labels: 🌳WOODY, D0
